# Generated by Django 4.2.4 on 2025-01-18 17:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('modulo_dot', '0001_initial'),
        ('login_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='statuses',
            name='usuario',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='modulo_dot.usuario'),
        ),
    ]
