# Generated by Django 4.2.4 on 2024-12-15 03:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0010_alter_usuariorol_role'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='usuariorol',
            unique_together={('username', 'role')},
        ),
    ]
