# Generated by Django 4.2.4 on 2024-12-15 04:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0011_alter_usuariorol_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='usuariorol',
            unique_together=set(),
        ),
    ]
