# Generated by Django 4.2.4 on 2024-12-21 04:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_dot', '0020_alter_usuario_usuario_rol'),
        ('login_app', '0012_alter_usuariorol_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('activo', 'activo'), ('pendiente', 'pendiente'), ('rechazado', 'rechazado')], max_length=10)),
                ('usuario', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='modulo_dot.usuario')),
            ],
            options={
                'db_table': 'Status',
            },
        ),
    ]
