# Generated by Django 4.2.4 on 2024-12-23 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0014_alter_usuariorol_password_alter_usuariorol_role_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuariorol',
            name='password',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
