# Generated by Django 4.2.4 on 2024-12-28 02:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_dot', '0035_alter_datospersonales_usuario'),
        ('login_app', '0015_alter_usuariorol_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='Statuses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('activa', 'Activa'), ('baja', 'Baja'), ('reincorporacion', 'Reincorporación'), ('reingreso', 'Reingreso'), ('suspendida', 'Suspendida')], default='suspendida', max_length=15)),
                ('usuario', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='modulo_dot.usuario')),
            ],
            options={
                'db_table': 'Statuses',
            },
        ),
        migrations.DeleteModel(
            name='Status',
        ),
    ]
