# Generated by Django 4.2.4 on 2024-12-28 06:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_dot', '0035_alter_datospersonales_usuario'),
        ('login_app', '0017_alter_statuses_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statuses',
            name='usuario',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='modulo_dot.usuario'),
        ),
    ]
