# Generated by Django 4.2.4 on 2025-01-13 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0018_alter_statuses_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statuses',
            name='status',
            field=models.CharField(choices=[('activa', 'Activa'), ('baja', 'Baja'), ('reincorporacion', 'Reincorporación'), ('reingreso', 'Reingreso'), ('suspendida', 'Suspendida'), ('capacitacion', 'Capacitacion')], default='suspendida', max_length=15),
        ),
    ]
