# Generated by Django 4.2.4 on 2024-12-29 04:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('cv_estado', models.CharField(max_length=5, primary_key=True, serialize=False, verbose_name='Clave única del estado')),
                ('nombre_estado', models.CharField(max_length=100, verbose_name='Nombre completo del estado')),
            ],
            options={
                'verbose_name': 'Estado',
                'verbose_name_plural': 'Estados',
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('cv_region', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='Clave única de la región')),
                ('nombre_region', models.CharField(max_length=100, verbose_name='Nombre completo de la región')),
                ('id_ecar', models.IntegerField(verbose_name='Identificador del responsable ECAR asignado')),
                ('cv_estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modulo_apec.estado', verbose_name='Clave del estado al que pertenece')),
            ],
            options={
                'verbose_name': 'Región',
                'verbose_name_plural': 'Regiones',
            },
        ),
        migrations.CreateModel(
            name='Microrregion',
            fields=[
                ('cv_microrregion', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='Clave única de la microrregión')),
                ('nombre_microrregion', models.CharField(max_length=100, verbose_name='Nombre completo de la microrregión')),
                ('id_eca', models.IntegerField(verbose_name='Identificador del responsable ECA asignado')),
                ('cv_region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modulo_apec.region', verbose_name='Clave de la región a la que pertenece')),
            ],
            options={
                'verbose_name': 'Microrregión',
                'verbose_name_plural': 'Microrregiones',
            },
        ),
        migrations.CreateModel(
            name='Comunidad',
            fields=[
                ('cv_comunidad', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='Clave única de la comunidad')),
                ('nombre_comunidad', models.CharField(max_length=100, verbose_name='Nombre completo de la comunidad')),
                ('contexto', models.TextField(verbose_name='Contexto social de la comunidad')),
                ('tipo_servicio', models.TextField(verbose_name='Tipo de servicio educativo que se ofrece')),
                ('id_ec', models.IntegerField(verbose_name='Identificador del responsable EC asignado')),
                ('cantidad_alumnos', models.IntegerField(verbose_name='Número de alumnos en la comunidad')),
                ('estatus', models.CharField(choices=[('Activo', 'Activo'), ('Inactivo', 'Inactivo')], max_length=8, verbose_name='Estado actual de la comunidad')),
                ('cv_microrregion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modulo_apec.microrregion', verbose_name='Clave de la microrregión a la que pertenece')),
            ],
            options={
                'verbose_name': 'Comunidad',
                'verbose_name_plural': 'Comunidades',
            },
        ),
    ]
