# Generated by Django 4.2.4 on 2025-01-20 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_apec', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comunidad',
            old_name='nombre_comunidad',
            new_name='Nombre',
        ),
        migrations.RenameField(
            model_name='comunidad',
            old_name='microrregion',
            new_name='claveMicroRegion',
        ),
        migrations.AddField(
            model_name='comunidad',
            name='id_Comunidad',
            field=models.IntegerField(blank=True, editable=False, null=True, unique=True),
        ),
    ]
