# Generated by Django 4.2.4 on 2025-01-05 23:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_apec', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicioeducativo',
            name='alumnos_hombres',
        ),
        migrations.RemoveField(
            model_name='servicioeducativo',
            name='alumnos_mujeres',
        ),
        migrations.RemoveField(
            model_name='servicioeducativo',
            name='alumnos_total',
        ),
        migrations.RemoveField(
            model_name='servicioeducativo',
            name='nombre_comite',
        ),
    ]
