# Generated by Django 4.2.4 on 2025-01-06 04:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_apec', '0002_remove_servicioeducativo_alumnos_hombres_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comunidad',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='comunidad',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='estado',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='estado',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='microrregion',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='microrregion',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='region',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='region',
            name='updated_at',
        ),
    ]
