# Generated by Django 4.2.4 on 2024-12-31 23:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_dot', '0036_alter_usuario_usuario_rol'),
        ('modulo_apec', '0002_alter_comunidad_options_alter_estado_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApoyoGestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_servicio_educativo', models.CharField(max_length=255)),
                ('numero_ec_asignado', models.IntegerField()),
                ('meses_servicio', models.IntegerField()),
                ('monto_apoyo_mensual', models.DecimalField(decimal_places=2, max_digits=10)),
                ('presupuesto_total_periodo', models.DecimalField(decimal_places=2, max_digits=15)),
                ('usuario', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='modulo_dot.usuario')),
            ],
        ),
        migrations.RemoveField(
            model_name='comunidad',
            name='id_ec',
        ),
        migrations.RemoveField(
            model_name='microrregion',
            name='id_eca',
        ),
        migrations.RemoveField(
            model_name='region',
            name='id_ecar',
        ),
        migrations.AddField(
            model_name='comunidad',
            name='usuario',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='modulo_dot.usuario'),
        ),
        migrations.AddField(
            model_name='microrregion',
            name='usuario',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='modulo_dot.usuario'),
        ),
        migrations.AddField(
            model_name='region',
            name='usuario',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='modulo_dot.usuario'),
        ),
        migrations.CreateModel(
            name='ServicioEducativo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_comite', models.CharField(max_length=255)),
                ('clave_municipio', models.CharField(max_length=255)),
                ('municipio', models.CharField(max_length=255)),
                ('clave_localidad', models.CharField(max_length=255)),
                ('localidad', models.CharField(max_length=255)),
                ('nivel_educativo', models.CharField(max_length=255)),
                ('clave_centro_trabajo', models.CharField(max_length=100)),
                ('apec_ini', models.CharField(choices=[('APEC', 'APEC'), ('APEC-INI', 'APEC-INI')], max_length=255)),
                ('alumnos_hombres', models.IntegerField()),
                ('alumnos_mujeres', models.IntegerField()),
                ('alumnos_total', models.IntegerField(editable=False)),
                ('monto_apoyo_mensual', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_periodo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('apoyo_gestion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='modulo_apec.apoyogestion')),
            ],
        ),
    ]
