# Generated by Django 4.2.4 on 2025-01-20 21:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_apec', '0002_rename_nombre_comunidad_comunidad_nombre_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comunidad',
            name='claveMicroRegion',
            field=models.ForeignKey(blank=True, db_column='claveMicroRegion', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comunidades', to='modulo_apec.microrregion', verbose_name='Microrregión a la que pertenece'),
        ),
    ]
