# Generated by Django 4.2.4 on 2025-01-06 07:01

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_apec', '0003_remove_comunidad_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comunidad',
            name='cantidad_alumnos',
        ),
        migrations.RemoveField(
            model_name='comunidad',
            name='estatus',
        ),
        migrations.RemoveField(
            model_name='comunidad',
            name='usuario',
        ),
        migrations.RemoveField(
            model_name='microrregion',
            name='usuario',
        ),
        migrations.RemoveField(
            model_name='region',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='region',
            name='usuario',
        ),
        migrations.AlterField(
            model_name='comunidad',
            name='contexto_comunidad',
            field=models.CharField(choices=[('Sin asignar', 'Sin asignar'), ('Indígena', 'Indígena'), ('Mestizo', 'Mestizo'), ('Migrante', 'Migrante'), ('Circense', 'Circense'), ('Grupos Vulnerables', 'Grupos Vulnerables'), ('Excluidos del Sistema Regular', 'Excluidos del Sistema Regular')], default='Sin asignar', max_length=255, verbose_name='Contexto de la comunidad'),
        ),
        migrations.AlterField(
            model_name='comunidad',
            name='microrregion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comunidades', to='modulo_apec.microrregion', verbose_name='Microrregión a la que pertenece'),
        ),
        migrations.CreateModel(
            name='Municipio',
            fields=[
                ('cv_municipio', models.CharField(max_length=10, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator(message='Solo se permiten letras y números.', regex='^[A-Za-z0-9]+$')], verbose_name='Clave única del municipio')),
                ('nombre_municipio', models.CharField(max_length=100, verbose_name='Nombre completo del municipio')),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='municipios', to='modulo_apec.estado', verbose_name='Estado al que pertenece')),
            ],
            options={
                'db_table': 'municipio',
            },
        ),
        migrations.AddField(
            model_name='region',
            name='municipios_region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='regiones', to='modulo_apec.municipio', verbose_name='Municipio al que pertenece'),
        ),
    ]
