# Generated by Django 4.2.4 on 2024-12-31 23:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_apec', '0003_apoyogestion_remove_comunidad_id_ec_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='apoyogestion',
            table='apoyo_gestion',
        ),
        migrations.AlterModelTable(
            name='servicioeducativo',
            table='servicio_educativo',
        ),
    ]
