# Generated by Django 4.2.4 on 2025-01-21 02:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_apec', '0003_alter_comunidad_clavemicroregion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comunidad',
            old_name='Nombre',
            new_name='nombre_comunidad',
        ),
        migrations.RemoveField(
            model_name='comunidad',
            name='claveMicroRegion',
        ),
        migrations.RemoveField(
            model_name='comunidad',
            name='id_Comunidad',
        ),
        migrations.AddField(
            model_name='comunidad',
            name='microrregion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comunidades', to='modulo_apec.microrregion', verbose_name='Microrregión a la que pertenece'),
        ),
    ]
