# Generated by Django 4.2.4 on 2025-01-06 07:08

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_dot', '0036_alter_usuario_usuario_rol'),
        ('modulo_apec', '0004_remove_comunidad_cantidad_alumnos_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='region',
            name='municipios_region',
        ),
        migrations.AddField(
            model_name='comunidad',
            name='cantidad_alumnos',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Número de alumnos en la comunidad'),
        ),
        migrations.AddField(
            model_name='comunidad',
            name='estatus',
            field=models.CharField(blank=True, choices=[('Activo', 'Activo'), ('Inactivo', 'Inactivo')], max_length=8, null=True, verbose_name='Estado actual de la comunidad'),
        ),
        migrations.AddField(
            model_name='comunidad',
            name='usuario',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='modulo_dot.usuario'),
        ),
        migrations.AddField(
            model_name='microrregion',
            name='usuario',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='modulo_dot.usuario'),
        ),
        migrations.AddField(
            model_name='region',
            name='estado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='regiones', to='modulo_apec.estado', verbose_name='Estado al que pertenece'),
        ),
        migrations.AddField(
            model_name='region',
            name='usuario',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='modulo_dot.usuario'),
        ),
        migrations.AlterField(
            model_name='comunidad',
            name='contexto_comunidad',
            field=models.CharField(blank=True, choices=[('Sin asignar', 'Sin asignar'), ('Indígena', 'Indígena'), ('Mestizo', 'Mestizo'), ('Migrante', 'Migrante'), ('Circense', 'Circense'), ('Grupos Vulnerables', 'Grupos Vulnerables'), ('Excluidos del Sistema Regular', 'Excluidos del Sistema Regular')], default='Sin asignar', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='comunidad',
            name='microrregion',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comunidades', to='modulo_apec.microrregion', verbose_name='Microrregión a la que pertenece'),
        ),
        migrations.AlterField(
            model_name='comunidad',
            name='tipo_servicio',
            field=models.TextField(blank=True, null=True, verbose_name='Tipo de servicio educativo que se ofrece'),
        ),
        migrations.AlterField(
            model_name='servicioeducativo',
            name='clave_estado',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='servicioeducativo',
            name='clave_region',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='servicioeducativo',
            name='contexto',
            field=models.CharField(blank=True, choices=[('Sin asignar', 'Sin asignar'), ('Rural', 'Rural'), ('Urbano', 'Urbano'), ('Indígena', 'Indígena'), ('Mestizo', 'Mestizo'), ('Migrante', 'Migrante'), ('Circense', 'Circense'), ('Grupos Vulnerables', 'Grupos Vulnerables'), ('Excluidos del Sistema Regular', 'Excluidos del Sistema Regular')], default='Sin asignar', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='servicioeducativo',
            name='nivel_educativo',
            field=models.CharField(blank=True, choices=[('APEC', 'APEC'), ('APEC-INI', 'APEC-INI')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='servicioeducativo',
            name='periodo_servicio',
            field=models.CharField(blank=True, choices=[('sin asignar', 'sin asignar'), ('2024-2025', '2024-2025'), ('2025-2026', '2025-2026')], default='sin asignar', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='servicioeducativo',
            name='rol_vacante',
            field=models.CharField(blank=True, choices=[('EC', 'Educador Comunitario'), ('ECA', 'Educador Comunitario de Acompañamiento Microrregional'), ('ECAR', 'Educador Comunitario de Acompañamiento Regional')], default='EC', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='servicioeducativo',
            name='tipo_servicio',
            field=models.CharField(blank=True, choices=[('Sin asignar', 'Sin asignar'), ('Inicial', 'Inicial'), ('Preescolar', 'Preescolar'), ('Primaria', 'Primaria'), ('Secundaria', 'Secundaria'), ('Postsecundaria', 'Postsecundaria')], default='Sin asignar', max_length=255, null=True),
        ),
        migrations.DeleteModel(
            name='Municipio',
        ),
    ]
