# Generated by Django 4.2.4 on 2025-01-01 00:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_apec', '0004_alter_apoyogestion_table_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicioeducativo',
            name='monto_apoyo_mensual',
        ),
        migrations.RemoveField(
            model_name='servicioeducativo',
            name='total_periodo',
        ),
    ]
