# Generated by Django 4.2.4 on 2025-01-06 07:16

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_apec', '0005_remove_region_municipios_region_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Municipio',
            fields=[
                ('cv_municipio', models.CharField(max_length=10, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator(message='Solo se permiten letras y números.', regex='^[A-Za-z0-9]+$')], verbose_name='Clave única del municipio')),
                ('nombre_municipio', models.CharField(max_length=100, verbose_name='Nombre completo del municipio')),
                ('estado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='municipios', to='modulo_apec.estado', verbose_name='Estado al que pertenece')),
            ],
            options={
                'db_table': 'municipio',
            },
        ),
        migrations.AddField(
            model_name='region',
            name='municipio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='regiones', to='modulo_apec.municipio', verbose_name='Municipio al que pertenece'),
        ),
    ]
