# Generated by Django 4.2.4 on 2025-01-01 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_apec', '0005_remove_servicioeducativo_monto_apoyo_mensual_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicioeducativo',
            name='contexto',
            field=models.CharField(choices=[('Sin asignar', 'Sin asignar'), ('Indígena', 'Indígena'), ('Mestizo', 'Mestizo'), ('Migrante', 'Migrante'), ('Circense', 'Circense'), ('Grupos Vulnerables', 'Grupos Vulnerables'), ('Excluidos del Sistema Regular', 'Excluidos del Sistema Regular')], default='Sin asignar', max_length=255),
        ),
        migrations.AddField(
            model_name='servicioeducativo',
            name='periodo_servicio',
            field=models.CharField(choices=[('sin asignar', 'sin asignar'), ('2024-2025', '2024-2025'), ('2025-2026', '2025-2026')], default='sin asignar', max_length=255),
        ),
        migrations.AddField(
            model_name='servicioeducativo',
            name='tipo_servicio',
            field=models.CharField(choices=[('Sin asignar', 'Sin asignar'), ('Inicial', 'Inicial'), ('Preescolar', 'Preescolar'), ('Primaria', 'Primaria'), ('Secundaria', 'Secundaria'), ('Postsecundaria', 'Postsecundaria')], default='Sin asignar', max_length=255),
        ),
    ]
