# Generated by Django 4.2.4 on 2025-01-01 23:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_apec', '0006_servicioeducativo_contexto_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='servicioeducativo',
            old_name='clave_localidad',
            new_name='clave_comunidad',
        ),
        migrations.RenameField(
            model_name='servicioeducativo',
            old_name='clave_municipio',
            new_name='clave_estado',
        ),
        migrations.RenameField(
            model_name='servicioeducativo',
            old_name='localidad',
            new_name='clave_region',
        ),
        migrations.RenameField(
            model_name='servicioeducativo',
            old_name='municipio',
            new_name='nombre_microregion',
        ),
        migrations.RemoveField(
            model_name='servicioeducativo',
            name='apec_ini',
        ),
        migrations.AddField(
            model_name='servicioeducativo',
            name='clave_microregion',
            field=models.CharField(default='Región', max_length=255),
        ),
        migrations.AddField(
            model_name='servicioeducativo',
            name='comunidad_servicio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='modulo_apec.comunidad'),
        ),
        migrations.AddField(
            model_name='servicioeducativo',
            name='nombre_comunidad',
            field=models.CharField(default='Nombre genérico', max_length=255),
        ),
        migrations.AddField(
            model_name='servicioeducativo',
            name='nombre_estado',
            field=models.CharField(default='Estado', max_length=255),
        ),
        migrations.AddField(
            model_name='servicioeducativo',
            name='nombre_region',
            field=models.CharField(default='Región', max_length=255),
        ),
        migrations.AddField(
            model_name='servicioeducativo',
            name='rol_vacante',
            field=models.CharField(choices=[('EC', 'Educador Comunitario'), ('ECA', 'Educador Comunitario de Acompañamiento Microrregional'), ('ECAR', 'Educador Comunitario de Acompañamiento Regional')], default='EC', max_length=10),
        ),
        migrations.AlterField(
            model_name='servicioeducativo',
            name='clave_centro_trabajo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='servicioeducativo',
            name='nivel_educativo',
            field=models.CharField(choices=[('APEC', 'APEC'), ('APEC-INI', 'APEC-INI')], max_length=255),
        ),
        migrations.AlterField(
            model_name='servicioeducativo',
            name='nombre_comite',
            field=models.CharField(default='Nombre comite genérico', max_length=255),
        ),
    ]
