# Generated by Django 4.2.4 on 2025-01-06 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_apec', '0006_municipio_region_municipio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comunidad',
            name='cantidad_alumnos',
        ),
    ]
