# Generated by Django 4.2.4 on 2025-01-07 05:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_apec', '0007_remove_comunidad_cantidad_alumnos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='region',
            name='municipio',
        ),
        migrations.AddField(
            model_name='comunidad',
            name='archivo',
            field=models.FileField(blank=True, null=True, upload_to='comunidades/', verbose_name='Archivo asociado a la comunidad'),
        ),
        migrations.AddField(
            model_name='region',
            name='municipios_region',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Municipios que pertenecen a la región'),
        ),
        migrations.AlterField(
            model_name='comunidad',
            name='microrregion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comunidades', to='modulo_apec.microrregion', verbose_name='Microrregión a la que pertenece'),
        ),
    ]
