# Generated by Django 4.2.4 on 2025-01-07 05:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_apec', '0008_remove_region_municipio_comunidad_archivo_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comunidad',
            old_name='archivo',
            new_name='localizacion',
        ),
    ]
