# Generated by Django 4.2.4 on 2025-01-03 00:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_apec', '0008_observacion'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='observacion',
            table='observacion',
        ),
    ]
