# Generated by Django 4.2.4 on 2025-01-13 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_apec', '0009_rename_archivo_comunidad_localizacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicioeducativo',
            name='cantidad_educadores_activos',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='servicioeducativo',
            name='cantidad_solicitudes',
            field=models.IntegerField(default=0),
        ),
    ]
