# Generated by Django 4.2.4 on 2025-01-14 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_apec', '0010_servicioeducativo_cantidad_educadores_activos_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicioeducativo',
            name='contexto',
        ),
        migrations.RemoveField(
            model_name='servicioeducativo',
            name='nivel_educativo',
        ),
        migrations.AddField(
            model_name='servicioeducativo',
            name='nivel_escolar',
            field=models.CharField(blank=True, choices=[('primaria I', 'Primaria I'), ('primaria II', 'Primaria II'), ('primaria III', 'Primaria III'), ('secundaria', 'Secundaria'), ('inicial', 'Inicial')], max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='servicioeducativo',
            name='nombre_escuela',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='servicioeducativo',
            name='tipo_sede',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='servicioeducativo',
            name='rol_vacante',
            field=models.CharField(blank=True, choices=[('EC', 'Educador Comunitario'), ('ECA', 'Educador Comunitario de Acompañamiento Microrregional'), ('ECAR', 'Educador Comunitario de Acompañamiento Regional')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='servicioeducativo',
            name='tipo_servicio',
            field=models.CharField(blank=True, choices=[('preescolar', 'Preescolar'), ('primaria', 'Primaria'), ('secundaria', 'Secundaria')], max_length=255, null=True),
        ),
    ]
