# Generated by Django 4.2.4 on 2025-01-03 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_dot', '0036_alter_usuario_usuario_rol'),
        ('modulo_apec', '0011_alter_observacion_candidatos_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='observacion',
            name='candidatos',
            field=models.ManyToManyField(blank=True, related_name='observaciones', to='modulo_dot.usuario'),
        ),
    ]
