# Generated by Django 4.2.4 on 2025-01-15 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_apec', '0011_remove_servicioeducativo_contexto_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicioeducativo',
            name='nivel_escolar',
        ),
        migrations.RemoveField(
            model_name='servicioeducativo',
            name='nombre_escuela',
        ),
        migrations.RemoveField(
            model_name='servicioeducativo',
            name='tipo_sede',
        ),
        migrations.AddField(
            model_name='servicioeducativo',
            name='contexto',
            field=models.CharField(blank=True, choices=[('Sin asignar', 'Sin asignar'), ('Rural', 'Rural'), ('Urbano', 'Urbano'), ('Indígena', 'Indígena'), ('Mestizo', 'Mestizo'), ('Migrante', 'Migrante'), ('Circense', 'Circense'), ('Grupos Vulnerables', 'Grupos Vulnerables'), ('Excluidos del Sistema Regular', 'Excluidos del Sistema Regular')], default='Sin asignar', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='servicioeducativo',
            name='nivel_educativo',
            field=models.CharField(blank=True, choices=[('APEC', 'APEC'), ('APEC-INI', 'APEC-INI')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='servicioeducativo',
            name='rol_vacante',
            field=models.CharField(blank=True, choices=[('EC', 'Educador Comunitario'), ('ECA', 'Educador Comunitario de Acompañamiento Microrregional'), ('ECAR', 'Educador Comunitario de Acompañamiento Regional')], default='EC', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='servicioeducativo',
            name='tipo_servicio',
            field=models.CharField(blank=True, choices=[('Sin asignar', 'Sin asignar'), ('Inicial', 'Inicial'), ('Preescolar', 'Preescolar'), ('Primaria', 'Primaria'), ('Secundaria', 'Secundaria'), ('Postsecundaria', 'Postsecundaria')], default='Sin asignar', max_length=255, null=True),
        ),
    ]
