# Generated by Django 4.2.4 on 2025-01-03 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_apec', '0012_alter_observacion_candidatos'),
    ]

    operations = [
        migrations.AddField(
            model_name='observacion',
            name='fecha_creacion',
            field=models.DateField(blank=True, null=True),
        ),
    ]
