# Generated by Django 4.2.4 on 2025-01-03 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_apec', '0013_observacion_fecha_creacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comunidad',
            name='contexto',
        ),
        migrations.AddField(
            model_name='comunidad',
            name='contexto_comunidad',
            field=models.CharField(choices=[('Sin asignar', 'Sin asignar'), ('Indígena', 'Indígena'), ('Mestizo', 'Mestizo'), ('Migrante', 'Migrante'), ('Circense', 'Circense'), ('Grupos Vulnerables', 'Grupos Vulnerables'), ('Excluidos del Sistema Regular', 'Excluidos del Sistema Regular')], default='Sin asignar', max_length=255),
        ),
    ]
