# Generated by Django 4.2.4 on 2025-01-15 17:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_dot', '0038_alter_datosusuario_id_comunidad'),
        ('modulo_apec', '0013_remove_servicioeducativo_contexto_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DatosComplementarios',
            fields=[
                ('id_SituacionEducativa', models.AutoField(primary_key=True, serialize=False)),
                ('situacionEducativa', models.CharField(blank=True, max_length=100, null=True)),
                ('CCT', models.CharField(blank=True, max_length=45, null=True)),
                ('contexto', models.CharField(blank=True, max_length=80, null=True)),
                ('nivel', models.CharField(blank=True, max_length=45, null=True)),
                ('Microregion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='datos_complementarios', to='modulo_apec.microrregion')),
                ('Region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='datos_complementarios', to='modulo_apec.region')),
                ('id_Usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='datos_complementarios', to='modulo_dot.usuario')),
            ],
            options={
                'verbose_name': 'Dato Complementario',
                'verbose_name_plural': 'Datos Complementarios',
                'db_table': 'datos_complementarios',
            },
        ),
    ]
