# Generated by Django 4.2.4 on 2025-01-03 19:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_apec', '0014_remove_comunidad_contexto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='observacion',
            name='servicio_educativo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='observaciones', to='modulo_apec.servicioeducativo'),
        ),
    ]
