# Generated by Django 4.2.4 on 2025-01-15 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_apec', '0014_datoscomplementarios'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='microrregion',
            name='usuario',
        ),
        migrations.RemoveField(
            model_name='region',
            name='usuario',
        ),
    ]
