# Generated by Django 4.2.4 on 2025-01-03 19:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_apec', '0015_alter_observacion_servicio_educativo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='observacion',
            name='servicio_educativo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='modulo_apec.servicioeducativo'),
        ),
    ]
