# Generated by Django 4.2.4 on 2025-01-16 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_apec', '0015_remove_microrregion_usuario_remove_region_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicioeducativo',
            name='status',
            field=models.CharField(blank=True, choices=[('aprobado', 'Aprobado'), ('rechazado', 'Rechazado')], default='Rechazado', max_length=10, null=True),
        ),
    ]
