# Generated by Django 4.2.4 on 2025-01-16 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_apec', '0016_servicioeducativo_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicioeducativo',
            name='status',
            field=models.CharField(blank=True, choices=[('aprobado', 'Aprobado'), ('rechazado', 'Rechazado'), ('pendiente', 'Pendiente')], default='Pendiente', max_length=10, null=True),
        ),
    ]
