# Generated by Django 4.2.4 on 2025-01-20 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_dpe', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pagosfechas',
            old_name='fecha',
            new_name='fechaPago',
        ),
    ]
