# Generated by Django 4.2.4 on 2025-01-06 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_dpe', '0002_alter_asistencia_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='reporte',
            name='categoria',
            field=models.CharField(choices=[('capacitación', 'Capacitación'), ('equipamiento', 'Equipamiento'), ('seguimiento', 'Seguimiento'), ('sin_asignar', 'Sin asignar')], default='sin_asignar', max_length=50),
        ),
        migrations.AlterField(
            model_name='reporte',
            name='estado',
            field=models.CharField(default='pendiente', max_length=50),
        ),
    ]
