# Generated by Django 4.2.4 on 2025-01-20 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_dpe', '0002_rename_fecha_pagosfechas_fechapago'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pagosfechas',
            old_name='fechaPago',
            new_name='fecha',
        ),
    ]
