# Generated by Django 4.2.4 on 2025-01-16 05:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_apec', '0017_alter_servicioeducativo_status'),
        ('modulo_dpe', '0003_reporte_categoria_alter_reporte_estado'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromocionesAlumnos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipoPromocion', models.CharField(max_length=50)),
                ('Grado', models.CharField(max_length=50)),
                ('Nivel', models.CharField(max_length=50)),
                ('id_Alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modulo_apec.comunidad')),
            ],
            options={
                'db_table': 'PromocionesAlumnos',
            },
        ),
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('id_Grupo', models.AutoField(primary_key=True, serialize=False)),
                ('Grado', models.DateField()),
                ('id_CCT', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modulo_apec.comunidad')),
            ],
            options={
                'db_table': 'grupos',
            },
        ),
    ]
