# Generated by Django 4.2.4 on 2025-01-16 05:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_dpe', '0004_promocionesalumnos_grupo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PromocionesAlumnos',
        ),
    ]
