# Generated by Django 4.2.4 on 2025-01-16 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_dpe', '0006_promocionesalumnos'),
    ]

    operations = [
        migrations.AddField(
            model_name='promocionesalumnos',
            name='calfFinal',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
