# Generated by Django 4.2.4 on 2025-01-06 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_coordinador', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActividadCalendario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('fecha_inicio', models.DateTimeField()),
                ('fecha_fin', models.DateTimeField()),
            ],
        ),
    ]
