# Generated by Django 4.2.4 on 2025-01-19 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_coordinador', '0002_alter_conveniosfiguras_tipo_convenio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conveniosfiguras',
            name='tipo_convenio',
            field=models.CharField(choices=[('CUD', 'CUD'), ('Inicial', 'Inicial'), ('Otro', 'Rechazado')], default='Inicial', max_length=50),
        ),
    ]
