# Generated by Django 4.2.4 on 2025-01-12 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_coordinador', '0003_alter_actividadcalendario_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='conveniosfiguras',
            name='control_numero',
            field=models.CharField(blank=True, max_length=150, null=True, unique=True),
        ),
    ]
