# Generated by Django 4.2.4 on 2025-01-19 05:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_dot', '0001_initial'),
        ('modulo_coordinador', '0003_alter_conveniosfiguras_tipo_convenio'),
    ]

    operations = [
        migrations.AddField(
            model_name='conveniosfiguras',
            name='firmado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='firmado_por', to='modulo_dot.usuario'),
        ),
    ]
