# Generated by Django 5.1.4 on 2025-01-12 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_coordinador', '0004_estado_microregion_comunidad_region_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='region',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='microregion',
            name='region',
        ),
        migrations.DeleteModel(
            name='Comunidad',
        ),
        migrations.DeleteModel(
            name='Estado',
        ),
        migrations.DeleteModel(
            name='Microregion',
        ),
        migrations.DeleteModel(
            name='Region',
        ),
    ]
