# Generated by Django 4.2.4 on 2025-01-12 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_coordinador', '0004_conveniosfiguras_control_numero'),
    ]

    operations = [
        migrations.AddField(
            model_name='conveniosfiguras',
            name='estado_convenio',
            field=models.CharField(choices=[('Pendiente', 'Pendiente'), ('Aprobado', 'Aprobado'), ('Rechazado', 'Rechazado')], default='Pendiente', max_length=50),
        ),
    ]
