# Generated by Django 4.2.4 on 2025-01-12 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_coordinador', '0005_conveniosfiguras_estado_convenio'),
    ]

    operations = [
        migrations.AddField(
            model_name='conveniosfiguras',
            name='tipo_convenio',
            field=models.CharField(choices=[('CUD', 'CUD'), ('Inicial', 'Inicial'), ('Otro', 'Otro')], default='Otro', max_length=50),
        ),
    ]
