# Generated by Django 5.1.4 on 2025-01-12 20:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_capacitacion', '0001_initial'),
        ('modulo_coordinador', '0005_remove_region_estado_remove_microregion_region_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoordinadorCapacitacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado_aprobacion', models.BooleanField(default=False)),
                ('capacitacion', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='modulo_capacitacion.capacitacioninicial')),
            ],
        ),
    ]
