# Generated by Django 5.1.4 on 2025-01-12 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_coordinador', '0006_coordinadorcapacitacion'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CoordinadorCapacitacion',
        ),
    ]
