# Generated by Django 4.2.4 on 2025-01-15 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_coordinador', '0008_alter_conveniosfiguras_tipo_convenio'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ActividadCalendario',
        ),
    ]
