# Generated by Django 5.1.4 on 2024-12-18 08:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_type', models.CharField(choices=[('AEPE', 'Apoyo Económico por Práctica Educativa'), ('AEP', 'Apoyo Económico Paralelo'), ('VEST', 'Vestuario'), ('MOVIL', 'Conectividad Móvil'), ('MEDICO', 'Atención Médica'), ('FIN', 'Fin de Año')], max_length=10)),
                ('payment_date', models.DateField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
