# Generated by Django 5.1.4 on 2024-12-18 09:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_DECB', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentschedule',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='paymentschedule',
            name='assigned_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='paymentschedule',
            name='payment_type',
            field=models.CharField(max_length=255),
        ),
    ]
