# Generated by Django 5.1.4 on 2024-12-18 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_DECB', '0002_remove_paymentschedule_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentschedule',
            name='payment_type',
            field=models.CharField(choices=[('Pago por Servicio', 'Pago por Servicio'), ('Transporte', 'Transporte'), ('Gastos Médicos', 'Gastos Médicos'), ('Apoyo Económico', 'Apoyo Económico'), ('Vivienda', 'Vivienda'), ('Material Didáctico', 'Material Didáctico')], max_length=50),
        ),
    ]
