# Generated by Django 5.1.4 on 2024-12-29 00:28

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_DECB', '0003_alter_paymentschedule_payment_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentschedule',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paymentschedule',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='paymentschedule',
            name='payment_type',
            field=models.CharField(choices=[('service_payment', 'Pago por Servicio'), ('transport', 'Transporte'), ('medical_expenses', 'Gastos Médicos')], max_length=50),
        ),
    ]
