# Generated by Django 5.1.4 on 2024-12-29 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_DECB', '0004_paymentschedule_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentschedule',
            name='payment_type',
            field=models.CharField(choices=[('movilidad', 'Movilidad'), ('hospedaje', 'Hospedaje y alimentos para la formación'), ('continuidad', 'Continuidad de estudios de manera paralela a la práctica educativa'), ('conectividad', 'Conectividad móvil'), ('vestuario', 'Vestuario de identidad para los EC'), ('atencion_medica', 'Apoyo económico para la atención médico-quirúrgica farmacéutica y hospitalaria'), ('fin_de_año', 'Apoyo económico de fin de año sujeto a la disposición presupuestal'), ('fallecimiento', 'Apoyo a beneficiario por fallecimiento')], max_length=50),
        ),
    ]
