# Generated by Django 4.2.4 on 2025-01-19 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_DECB', '0004_paymentstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentschedule',
            name='payment_date_pay',
            field=models.DateField(blank=True, default='2025-01-01', null=True),
        ),
    ]
