# Generated by Django 5.1.4 on 2024-12-30 07:02

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_DECB', '0005_alter_paymentschedule_payment_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('payment_schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial_pagos', to='modulo_DECB.paymentschedule')),
            ],
            options={
                'verbose_name': 'Historial de Pago',
                'verbose_name_plural': 'Historial de Pagos',
                'db_table': 'payment_history',
            },
        ),
    ]
