# Generated by Django 4.2.4 on 2025-01-19 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_DECB', '0005_paymentschedule_payment_date_pay'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentschedule',
            name='payment_date_pay',
        ),
    ]
