# Generated by Django 5.1.4 on 2024-12-30 23:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_DECB', '0008_remove_paymentschedule_created_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paymenthistory',
            options={},
        ),
        migrations.AlterField(
            model_name='paymenthistory',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='paymentschedule',
            name='assigned_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments_assigned_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='paymentschedule',
            name='assigned_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments_assigned_to', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='paymentschedule',
            name='payment_type',
            field=models.CharField(choices=[('movilidad', 'Movilidad'), ('hospedaje', 'Hospedaje y alimentos para la formación'), ('continuidad', 'Continuidad de estudios'), ('conectividad', 'Conectividad móvil'), ('vestuario', 'Vestuario de identidad'), ('atencion_medica', 'Atención médico-quirúrgica'), ('fin_de_año', 'Apoyo de fin de año'), ('fallecimiento', 'Apoyo por fallecimiento')], max_length=50),
        ),
        migrations.AlterModelTable(
            name='paymenthistory',
            table=None,
        ),
    ]
