# Generated by Django 5.1.4 on 2024-12-31 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_DECB', '0010_paymentschedule_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentschedule',
            name='signature',
            field=models.ImageField(blank=True, null=True, upload_to='signatures/'),
        ),
    ]
