# Generated by Django 5.1.4 on 2025-01-04 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_DECB', '0011_paymentschedule_signature'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentschedule',
            name='payment_type',
            field=models.CharField(choices=[('movilidad', 'Movilidad'), ('hospedaje', 'Hospedaje y alimentos para la formación'), ('continuidad', 'Continuidad de estudios'), ('conectividad', 'Conectividad móvil'), ('vestuario', 'Vestuario de identidad'), ('atencion_medica', 'Atención médica'), ('fin_de_año', 'Apoyo económico de fin de año'), ('fallecimiento', 'Apoyo a beneficiarios por fallecimiento')], max_length=50),
        ),
    ]
