# Generated by Django 5.1.4 on 2025-01-04 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_DECB', '0012_alter_paymentschedule_payment_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalendarEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('inicio_ciclo', 'Inicio de Ciclo Escolar'), ('termino_ciclo', 'Término de Ciclo Escolar'), ('colegiado_regional', 'Colegiado Regional'), ('colegiado_microrregional', 'Colegiado Microrregional'), ('promocion_captacion', 'Promoción y Captación'), ('capacitacion', 'Capacitación')], max_length=50)),
                ('date', models.DateField()),
                ('description', models.TextField(blank=True)),
            ],
        ),
    ]
