# Generated by Django 4.2.4 on 2024-12-21 04:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('modulo_dot', '0020_alter_usuario_usuario_rol'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aspirante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folio', models.CharField(blank=True, max_length=150, unique=True)),
                ('rol', models.CharField(default='Aspirante', max_length=10)),
                ('telefono', models.CharField(blank=True, max_length=15)),
                ('datos_personales', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='modulo_dot.datospersonales')),
            ],
            options={
                'db_table': 'Aspirante',
            },
        ),
        migrations.CreateModel(
            name='Residencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_postal', models.CharField(max_length=10)),
                ('estado', models.CharField(max_length=100)),
                ('municipio_alcaldia', models.CharField(max_length=100)),
                ('localidad', models.CharField(blank=True, max_length=100, null=True)),
                ('colonia', models.CharField(max_length=100)),
                ('calle', models.CharField(max_length=100)),
                ('aspirante', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='form_app.aspirante')),
            ],
        ),
        migrations.CreateModel(
            name='Participacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado_participacion', models.CharField(max_length=100)),
                ('ciclo_escolar', models.CharField(max_length=100)),
                ('programa_participacion', models.CharField(default='EC', max_length=100)),
                ('tipo_servicio', models.CharField(max_length=100)),
                ('contexto', models.CharField(max_length=100)),
                ('aspirante', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='form_app.aspirante')),
            ],
        ),
        migrations.CreateModel(
            name='Gestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('habla_lengua_indigena', models.BooleanField(default=False)),
                ('lengua_indigena', models.CharField(blank=True, max_length=100, null=True)),
                ('talla_playera', models.CharField(max_length=10)),
                ('talla_pantalon', models.CharField(max_length=10)),
                ('talla_calzado', models.CharField(max_length=10)),
                ('peso', models.FloatField()),
                ('estatura', models.FloatField()),
                ('medio_entero', models.CharField(max_length=100)),
                ('aspirante', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='form_app.aspirante')),
            ],
        ),
        migrations.CreateModel(
            name='Banco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banco', models.CharField(blank=True, max_length=100, null=True)),
                ('cuenta_bancaria', models.CharField(blank=True, max_length=50, null=True)),
                ('aspirante', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='form_app.aspirante')),
            ],
        ),
    ]
