# Generated by Django 4.2.4 on 2024-12-21 04:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('form_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='banco',
            table='Informacion_Bancaria',
        ),
        migrations.AlterModelTable(
            name='gestion',
            table='Informacion_Gestion',
        ),
        migrations.AlterModelTable(
            name='participacion',
            table='Participacion',
        ),
        migrations.AlterModelTable(
            name='residencia',
            table='Residencia',
        ),
    ]
