# Generated by Django 4.2.4 on 2024-12-21 04:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('form_app', '0002_alter_banco_table_alter_gestion_table_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gestion',
            old_name='medio_entero',
            new_name='medio_publicitario',
        ),
    ]
