# Generated by Django 4.2.4 on 2024-12-22 02:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('form_app', '0003_rename_medio_entero_gestion_medio_publicitario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aspirante',
            name='telefono',
        ),
    ]
