# Generated by Django 4.2.4 on 2024-12-22 20:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_dot', '0021_alter_datospersonales_usuario'),
        ('form_app', '0004_remove_aspirante_telefono'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banco',
            name='aspirante',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='modulo_dot.datospersonales'),
        ),
        migrations.AlterField(
            model_name='gestion',
            name='aspirante',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='modulo_dot.datospersonales'),
        ),
        migrations.AlterField(
            model_name='participacion',
            name='aspirante',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='modulo_dot.datospersonales'),
        ),
        migrations.AlterField(
            model_name='residencia',
            name='aspirante',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='modulo_dot.datospersonales'),
        ),
    ]
