# Generated by Django 4.2.4 on 2024-12-22 21:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_dot', '0021_alter_datospersonales_usuario'),
        ('form_app', '0005_alter_banco_aspirante_alter_gestion_aspirante_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aspirante',
            name='datos_personales',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='aspirante_info', to='modulo_dot.datospersonales'),
        ),
    ]
