# Generated by Django 4.2.4 on 2024-12-22 21:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('form_app', '0006_alter_aspirante_datos_personales'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='aspirante',
            table='aspirante',
        ),
    ]
