# Generated by Django 4.2.4 on 2024-12-23 00:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_dot', '0029_alter_usuario_contrasenia'),
        ('form_app', '0009_remove_aspirante_rol_alter_aspirante_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='aspirante',
            name='usuario',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='modulo_dot.usuario'),
        ),
    ]
