# Generated by Django 4.2.4 on 2024-12-23 01:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('form_app', '0010_aspirante_usuario'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='aspirante',
            table='aspirante',
        ),
    ]
