# Generated by Django 4.2.4 on 2024-12-23 01:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('form_app', '0012_alter_banco_aspirante_alter_gestion_aspirante_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='aspirante',
            table='Aspirante',
        ),
    ]
