# Generated by Django 4.2.4 on 2024-12-23 01:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_dot', '0031_alter_usuario_contrasenia'),
        ('form_app', '0013_alter_aspirante_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banco',
            name='aspirante',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='modulo_dot.datospersonales'),
        ),
        migrations.AlterField(
            model_name='gestion',
            name='aspirante',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='modulo_dot.datospersonales'),
        ),
        migrations.AlterField(
            model_name='participacion',
            name='aspirante',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='modulo_dot.datospersonales'),
        ),
        migrations.AlterField(
            model_name='residencia',
            name='aspirante',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='modulo_dot.datospersonales'),
        ),
        migrations.AlterModelTable(
            name='aspirante',
            table='aspirante',
        ),
    ]
