# Generated by Django 4.2.4 on 2024-12-23 01:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_dot', '0032_remove_datospersonales_aspirante_and_more'),
        ('form_app', '0014_alter_banco_aspirante_alter_gestion_aspirante_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aspirante',
            name='usuario',
        ),
        migrations.AddField(
            model_name='aspirante',
            name='rol',
            field=models.CharField(default='Aspirante', max_length=10),
        ),
        migrations.AlterField(
            model_name='aspirante',
            name='datos_personales',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='modulo_dot.datospersonales'),
        ),
        migrations.AlterField(
            model_name='aspirante',
            name='folio',
            field=models.CharField(blank=True, max_length=150, unique=True),
        ),
        migrations.AlterField(
            model_name='banco',
            name='aspirante',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='form_app.aspirante'),
        ),
        migrations.AlterField(
            model_name='gestion',
            name='aspirante',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='form_app.aspirante'),
        ),
        migrations.AlterField(
            model_name='participacion',
            name='aspirante',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='form_app.aspirante'),
        ),
        migrations.AlterField(
            model_name='residencia',
            name='aspirante',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='form_app.aspirante'),
        ),
        migrations.AlterModelTable(
            name='aspirante',
            table='Aspirante',
        ),
    ]
