# Generated by Django 4.2.4 on 2024-12-23 02:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('form_app', '0015_remove_aspirante_usuario_aspirante_rol_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aspirante',
            name='rol',
        ),
    ]
