# Generated by Django 4.2.4 on 2024-12-23 02:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_dot', '0033_alter_usuario_contrasenia_alter_usuario_usuario'),
        ('form_app', '0016_remove_aspirante_rol'),
    ]

    operations = [
        migrations.AddField(
            model_name='aspirante',
            name='usuario',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='modulo_dot.usuario'),
        ),
        migrations.AlterField(
            model_name='banco',
            name='aspirante',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='modulo_dot.datospersonales'),
        ),
        migrations.AlterField(
            model_name='gestion',
            name='aspirante',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='modulo_dot.datospersonales'),
        ),
        migrations.AlterField(
            model_name='participacion',
            name='aspirante',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='modulo_dot.datospersonales'),
        ),
        migrations.AlterField(
            model_name='residencia',
            name='aspirante',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='modulo_dot.datospersonales'),
        ),
    ]
