# Generated by Django 4.2.4 on 2024-12-23 03:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('form_app', '0017_aspirante_usuario_alter_banco_aspirante_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banco',
            name='aspirante',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='form_app.aspirante'),
        ),
        migrations.AlterField(
            model_name='gestion',
            name='aspirante',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='form_app.aspirante'),
        ),
        migrations.AlterField(
            model_name='participacion',
            name='aspirante',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='form_app.aspirante'),
        ),
        migrations.AlterField(
            model_name='residencia',
            name='aspirante',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='form_app.aspirante'),
        ),
    ]
