# Generated by Django 4.2.4 on 2024-12-23 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form_app', '0018_alter_banco_aspirante_alter_gestion_aspirante_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aspirante',
            name='folio',
            field=models.CharField(blank=True, max_length=150, null=True, unique=True),
        ),
    ]
