# Generated by Django 4.2.4 on 2024-12-23 22:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('form_app', '0019_alter_aspirante_folio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='residencia',
            name='localidad',
        ),
    ]
