# Generated by Django 4.2.4 on 2024-12-24 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form_app', '0020_remove_residencia_localidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gestion',
            name='habla_lengua_indigena',
            field=models.BooleanField(),
        ),
    ]
