# Generated by Django 4.2.4 on 2024-12-27 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form_app', '0021_alter_gestion_habla_lengua_indigena'),
    ]

    operations = [
        migrations.AddField(
            model_name='residencia',
            name='Contexto',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='residencia',
            name='Tipo_de_servicio',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
