# Generated by Django 4.2.4 on 2024-12-27 01:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('form_app', '0022_residencia_contexto_residencia_tipo_de_servicio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='residencia',
            name='Contexto',
        ),
        migrations.RemoveField(
            model_name='residencia',
            name='Tipo_de_servicio',
        ),
    ]
