# Generated by Django 4.2.4 on 2024-12-27 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form_app', '0023_remove_residencia_contexto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participacion',
            name='programa_participacion',
            field=models.CharField(max_length=100),
        ),
    ]
