# Generated by Django 4.2.4 on 2024-12-28 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form_app', '0024_alter_participacion_programa_participacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='aspirante',
            name='status_seleccion',
            field=models.CharField(choices=[('activo', 'activo'), ('pendiente', 'pendiente'), ('rechazado', 'rechazado')], default='pendiente', max_length=10),
        ),
    ]
