# Generated by Django 4.2.4 on 2024-12-29 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form_app', '0026_alter_aspirante_status_seleccion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aspirante',
            name='status_seleccion',
            field=models.CharField(blank=True, choices=[('aceptado', 'aceptado'), ('pendiente', 'pendiente'), ('rechazado', 'rechazado')], default='pendiente', max_length=10, null=True),
        ),
    ]
