# Generated by Django 4.2.4 on 2025-01-21 11:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('modulo_dot', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActividadCalendario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('fecha_inicio', models.DateTimeField()),
                ('fecha_fin', models.DateTimeField()),
            ],
            options={
                'db_table': 'actividad_calendario',
            },
        ),
        migrations.CreateModel(
            name='ConveniosFiguras',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('convenio_pdf', models.FileField(blank=True, null=True, upload_to='documentos/')),
                ('firma_digital', models.FileField(blank=True, null=True, upload_to='firmas/')),
                ('usuario', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='modulo_dot.usuario')),
            ],
            options={
                'db_table': 'convenio_digital',
            },
        ),
    ]
