# Generated by Django 4.2.4 on 2025-01-18 17:13

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('modulo_dot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CapacitacionInicial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ciclo_asignado', models.CharField(max_length=20)),
                ('fecha', models.DateField()),
                ('contexto', models.TextField()),
                ('actividad', models.TextField()),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('en_curso', 'En Curso'), ('completada', 'Completada'), ('cancelada', 'Cancelada')], default='pendiente', max_length=20)),
                ('horas_cubiertas', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('ec', models.ForeignKey(blank=True, limit_choices_to={'rol': 'EC'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='capacitaciones_como_ec', to='modulo_dot.usuario')),
                ('ecar', models.ForeignKey(blank=True, limit_choices_to={'rol': 'ECAR'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='capacitaciones_como_ecar', to='modulo_dot.usuario')),
            ],
            options={
                'verbose_name': 'Capacitación Inicial',
                'verbose_name_plural': 'Capacitaciones Iniciales',
                'ordering': ['-fecha'],
            },
        ),
    ]
