# Generated by Django 5.1.4 on 2025-01-04 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CapacitacionInicial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cv_region', models.CharField(max_length=50)),
                ('nombre_ecar', models.CharField(max_length=100)),
                ('cv_microrregion', models.CharField(max_length=50)),
                ('nombre_eca', models.CharField(max_length=100)),
                ('cv_comunidad', models.CharField(max_length=50)),
                ('id_ec', models.CharField(max_length=20)),
                ('nombre_ec', models.CharField(max_length=100)),
                ('ciclo_asignado', models.CharField(max_length=50)),
                ('contexto', models.TextField()),
                ('tipo_servicio', models.CharField(max_length=50)),
                ('actividad', models.CharField(max_length=100)),
                ('fecha', models.DateField()),
                ('horas_cubiertas', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Capacitación Inicial',
                'verbose_name_plural': 'Capacitaciones Iniciales',
            },
        ),
    ]
