# Generated by Django 4.2.4 on 2025-01-19 22:34

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_dot', '0001_initial'),
        ('modulo_capacitacion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VacanteAsignada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puesto', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('fecha_asignacion', models.DateField()),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('Proceso', 'Proceso'), ('completada', 'Completada'), ('cancelada', 'Cancelada')], default='pendiente', max_length=20)),
                ('horas_asignadas', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('ciclo_asignado', models.CharField(blank=True, max_length=20, null=True)),
                ('actividad', models.TextField(blank=True, null=True)),
                ('contexto', models.TextField(blank=True, null=True)),
                ('horas_cubiertas', models.PositiveIntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('fecha', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('ec', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ec_vacantes', to='modulo_dot.usuario')),
                ('ecar', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ecar_vacantes', to='modulo_dot.usuario')),
                ('usuario_asignada', models.ForeignKey(blank=True, limit_choices_to={'rol': 'EC'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vacantes_responsables', to='modulo_dot.usuario')),
                ('usuario_responsable', models.ForeignKey(blank=True, limit_choices_to={'rol': 'ECAR'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vacantes_asignadas', to='modulo_dot.usuario')),
            ],
            options={
                'verbose_name': 'Vacante Asignada',
                'verbose_name_plural': 'Vacantes Asignadas',
                'ordering': ['-fecha_asignacion'],
            },
        ),
        migrations.DeleteModel(
            name='CapacitacionInicial',
        ),
    ]
