# Generated by Django 4.2.4 on 2025-01-13 17:33

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_dot', '0038_alter_datosusuario_id_comunidad'),
        ('modulo_capacitacion', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='capacitacioninicial',
            options={'ordering': ['-fecha'], 'verbose_name': 'Capacitación Inicial', 'verbose_name_plural': 'Capacitaciones Iniciales'},
        ),
        migrations.RemoveField(
            model_name='capacitacioninicial',
            name='cv_comunidad',
        ),
        migrations.RemoveField(
            model_name='capacitacioninicial',
            name='cv_microrregion',
        ),
        migrations.RemoveField(
            model_name='capacitacioninicial',
            name='cv_region',
        ),
        migrations.RemoveField(
            model_name='capacitacioninicial',
            name='id_ec',
        ),
        migrations.RemoveField(
            model_name='capacitacioninicial',
            name='nombre_ec',
        ),
        migrations.RemoveField(
            model_name='capacitacioninicial',
            name='nombre_eca',
        ),
        migrations.RemoveField(
            model_name='capacitacioninicial',
            name='nombre_ecar',
        ),
        migrations.RemoveField(
            model_name='capacitacioninicial',
            name='tipo_servicio',
        ),
        migrations.AddField(
            model_name='capacitacioninicial',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='capacitacioninicial',
            name='ec',
            field=models.ForeignKey(blank=True, limit_choices_to={'rol': 'EC'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='capacitaciones_como_ec', to='modulo_dot.usuario'),
        ),
        migrations.AddField(
            model_name='capacitacioninicial',
            name='ecar',
            field=models.ForeignKey(blank=True, limit_choices_to={'rol': 'ECAR'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='capacitaciones_como_ecar', to='modulo_dot.usuario'),
        ),
        migrations.AddField(
            model_name='capacitacioninicial',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('en_curso', 'En Curso'), ('completada', 'Completada'), ('cancelada', 'Cancelada')], default='pendiente', max_length=20),
        ),
        migrations.AddField(
            model_name='capacitacioninicial',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='capacitacioninicial',
            name='actividad',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='capacitacioninicial',
            name='ciclo_asignado',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='capacitacioninicial',
            name='horas_cubiertas',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
