# Generated by Django 5.1.4 on 2025-01-12 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_capacitacion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='capacitacioninicial',
            name='cct',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
