# Generated by Django 4.2.4 on 2025-01-20 01:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_dot', '0001_initial'),
        ('modulo_capacitacion', '0002_vacanteasignada_delete_capacitacioninicial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacanteasignada',
            name='usuario_asignada_eca',
            field=models.ForeignKey(blank=True, limit_choices_to={'rol': 'ECA'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vacantes_asignada_eca', to='modulo_dot.usuario'),
        ),
    ]
