# Generated by Django 5.1.4 on 2025-01-12 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_capacitacion', '0002_capacitacioninicial_cct'),
    ]

    operations = [
        migrations.AddField(
            model_name='capacitacioninicial',
            name='finalizada',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='capacitacioninicial',
            name='cct',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
