# Generated by Django 4.2.4 on 2025-01-20 02:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_capacitacion', '0003_vacanteasignada_usuario_asignada_eca'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vacanteasignada',
            name='usuario_asignada_eca',
        ),
    ]
