# Generated by Django 5.1.4 on 2025-01-12 21:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_capacitacion', '0003_capacitacioninicial_finalizada_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='capacitacioninicial',
            name='cct',
        ),
    ]
