# Generated by Django 4.2.4 on 2025-01-20 02:27

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_dot', '0001_initial'),
        ('modulo_capacitacion', '0004_remove_vacanteasignada_usuario_asignada_eca'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vacanteasignada',
            options={'verbose_name': 'Vacante Asignada', 'verbose_name_plural': 'Vacantes Asignadas'},
        ),
        migrations.RemoveField(
            model_name='vacanteasignada',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='vacanteasignada',
            name='descripcion',
        ),
        migrations.RemoveField(
            model_name='vacanteasignada',
            name='ec',
        ),
        migrations.RemoveField(
            model_name='vacanteasignada',
            name='ecar',
        ),
        migrations.RemoveField(
            model_name='vacanteasignada',
            name='fecha_asignacion',
        ),
        migrations.RemoveField(
            model_name='vacanteasignada',
            name='horas_asignadas',
        ),
        migrations.RemoveField(
            model_name='vacanteasignada',
            name='puesto',
        ),
        migrations.RemoveField(
            model_name='vacanteasignada',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='vacanteasignada',
            name='usuario_asignada',
        ),
        migrations.AddField(
            model_name='vacanteasignada',
            name='usuario_ec',
            field=models.ForeignKey(blank=True, limit_choices_to={'rol': 'EC'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vacantes_ec', to='modulo_dot.usuario'),
        ),
        migrations.AddField(
            model_name='vacanteasignada',
            name='usuario_eca',
            field=models.ForeignKey(blank=True, limit_choices_to={'rol': 'ECA'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vacantes_eca', to='modulo_dot.usuario'),
        ),
        migrations.AddField(
            model_name='vacanteasignada',
            name='vacante_asignada',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='vacanteasignada',
            name='actividad',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='vacanteasignada',
            name='ciclo_asignado',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vacanteasignada',
            name='contexto',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='vacanteasignada',
            name='estado',
            field=models.CharField(blank=True, choices=[('pendiente', 'Pendiente'), ('Proceso', 'Proceso'), ('completada', 'Completada'), ('cancelada', 'Cancelada')], default='pendiente', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='vacanteasignada',
            name='fecha',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vacanteasignada',
            name='horas_cubiertas',
            field=models.IntegerField(blank=True, help_text='Horas totales cubiertas de la capacitación', null=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
