# Generated by Django 5.1.4 on 2025-01-12 22:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_capacitacion', '0004_remove_capacitacioninicial_cct'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='capacitacioninicial',
            name='finalizada',
        ),
    ]
