# Generated by Django 5.1.4 on 2025-01-12 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_capacitacion', '0005_remove_capacitacioninicial_finalizada'),
    ]

    operations = [
        migrations.AddField(
            model_name='capacitacioninicial',
            name='cct',
            field=models.CharField(default='Default CCT', max_length=50, unique=True),
            preserve_default=False,
        ),
    ]
