# Generated by Django 5.1.4 on 2025-01-12 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_capacitacion', '0006_capacitacioninicial_cct'),
    ]

    operations = [
        migrations.AddField(
            model_name='capacitacioninicial',
            name='finalizada',
            field=models.BooleanField(default=False),
        ),
    ]
