# Generated by Django 4.2.4 on 2025-01-03 00:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('modulo_dot', '0036_alter_usuario_usuario_rol'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventoCalendario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_evento', models.CharField(choices=[('Inicio', 'Inicio'), ('Termino de ciclo', 'Termino de ciclo'), ('Colegiado', 'Colegiado')], max_length=50)),
                ('fecha_inicio', models.DateField()),
                ('fecha_termino', models.DateField()),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modulo_dot.usuario')),
            ],
            options={
                'db_table': 'evento_calendario',
            },
        ),
        migrations.CreateModel(
            name='CapacitacionInical',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contexto', models.CharField(max_length=255)),
                ('tipo_servicio', models.CharField(max_length=255)),
                ('actividad', models.CharField(max_length=255)),
                ('fecha_inicio', models.DateField()),
                ('horas_cubiertas', models.IntegerField()),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modulo_dot.usuario')),
            ],
            options={
                'db_table': 'capacitacion_inicial',
            },
        ),
    ]
