# Generated by Django 4.2.4 on 2025-01-08 03:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home_empleado', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActividadAcompMovil',
            fields=[
                ('id_ActividadAcomp', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('nombreEC', models.TextField()),
                ('descripcion', models.TextField()),
                ('estado', models.TextField()),
            ],
            options={
                'db_table': 'actividad_acomp_movil',
            },
        ),
        migrations.CreateModel(
            name='ActividadAlumnosMovil',
            fields=[
                ('id_ActAlum', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.TextField()),
                ('descripcion', models.TextField()),
                ('periodo', models.TextField()),
                ('materia', models.TextField()),
                ('estado', models.TextField()),
            ],
            options={
                'db_table': 'actividad_alumnos_movil',
            },
        ),
        migrations.CreateModel(
            name='AlumnosMovil',
            fields=[
                ('id_Alumno', models.AutoField(primary_key=True, serialize=False)),
                ('actaNacimiento', models.BinaryField(blank=True, null=True)),
                ('curp', models.TextField(blank=True, null=True)),
                ('fechaNacimiento', models.TextField(blank=True, null=True)),
                ('lugarNacimiento', models.TextField(blank=True, null=True)),
                ('domicilio', models.TextField(blank=True, null=True)),
                ('municipio', models.TextField(blank=True, null=True)),
                ('estado', models.TextField(blank=True, null=True)),
                ('nivelEducativo', models.TextField(blank=True, null=True)),
                ('gradoEscolar', models.TextField(blank=True, null=True)),
                ('certificadoEstudios', models.BinaryField(blank=True, null=True)),
                ('nombrePadre', models.TextField(blank=True, null=True)),
                ('ocupacionPadre', models.TextField(blank=True, null=True)),
                ('telefonoPadre', models.TextField(blank=True, null=True)),
                ('fotoVacunacion', models.BinaryField(blank=True, null=True)),
                ('state', models.TextField(blank=True, null=True)),
                ('nota', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'alumnos_movil',
            },
        ),
        migrations.CreateModel(
            name='ComunidadMovil',
            fields=[
                ('id_Comunidad', models.AutoField(primary_key=True, serialize=False)),
                ('claveMicroRegion', models.TextField()),
                ('Nombre', models.TextField()),
            ],
            options={
                'db_table': 'comunidad_movil',
            },
        ),
        migrations.CreateModel(
            name='DatosUsuariosMovil',
            fields=[
                ('id_Datos', models.AutoField(primary_key=True, serialize=False)),
                ('nombreCompleto', models.TextField()),
                ('situacion_Educativa', models.TextField(blank=True, null=True)),
                ('tipoServicio', models.TextField(blank=True, null=True)),
                ('contexto', models.TextField(blank=True, null=True)),
                ('Estado', models.BooleanField()),
                ('id_Comunidad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home_empleado.comunidadmovil')),
            ],
            options={
                'db_table': 'datos_usuarios_movil',
            },
        ),
        migrations.CreateModel(
            name='PromocionFechasMovil',
            fields=[
                ('id_PromoFechas', models.AutoField(primary_key=True, serialize=False)),
                ('promocionPDF', models.BinaryField()),
                ('fechas', models.TextField()),
            ],
            options={
                'db_table': 'promocion_fechas_movil',
            },
        ),
        migrations.CreateModel(
            name='UsuariosMovil',
            fields=[
                ('id_Usuario', models.AutoField(primary_key=True, serialize=False)),
                ('usuario', models.TextField()),
                ('password', models.TextField()),
                ('rol', models.TextField()),
                ('id_Datos', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home_empleado.datosusuariosmovil')),
            ],
            options={
                'db_table': 'usuarios_movil',
            },
        ),
        migrations.CreateModel(
            name='ReportesMovil',
            fields=[
                ('id_Reporte', models.AutoField(primary_key=True, serialize=False)),
                ('periodo', models.TextField()),
                ('estado', models.TextField()),
                ('reporte', models.BinaryField()),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home_empleado.usuariosmovil')),
            ],
            options={
                'db_table': 'reportes_movil',
            },
        ),
        migrations.CreateModel(
            name='ReportesAcompMovil',
            fields=[
                ('id_ReporteAcomp', models.AutoField(primary_key=True, serialize=False)),
                ('reporte', models.BinaryField()),
                ('fecha', models.DateField()),
                ('figuraEducativa', models.TextField()),
                ('id_ActividadAcomp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home_empleado.actividadacompmovil')),
                ('id_Usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home_empleado.usuariosmovil')),
            ],
            options={
                'db_table': 'reportes_acomp_movil',
            },
        ),
        migrations.CreateModel(
            name='RegistroMoviliarioMovil',
            fields=[
                ('id_RMoviliario', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.TextField()),
                ('cantidad', models.IntegerField()),
                ('condicion', models.TextField()),
                ('comentarios', models.TextField()),
                ('periodo', models.TextField()),
                ('id_Comunidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home_empleado.comunidadmovil')),
                ('id_Usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home_empleado.usuariosmovil')),
            ],
            options={
                'db_table': 'registro_moviliario_movil',
            },
        ),
        migrations.CreateModel(
            name='ReciboMovil',
            fields=[
                ('id_Recibo', models.AutoField(primary_key=True, serialize=False)),
                ('recibo', models.BinaryField()),
                ('tipoRecibo', models.TextField()),
                ('id_Usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home_empleado.usuariosmovil')),
            ],
            options={
                'db_table': 'recibo_movil',
            },
        ),
        migrations.CreateModel(
            name='PagosFechasMovil',
            fields=[
                ('id_PagoFecha', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('tipoPago', models.TextField()),
                ('monto', models.FloatField()),
                ('id_Usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home_empleado.usuariosmovil')),
            ],
            options={
                'db_table': 'pagos_fechas_movil',
            },
        ),
        migrations.CreateModel(
            name='DependenciasMovil',
            fields=[
                ('id_Dependencias', models.AutoField(primary_key=True, serialize=False)),
                ('id_Dependiente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dependiente', to='home_empleado.usuariosmovil')),
                ('id_Responsable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responsable', to='home_empleado.usuariosmovil')),
            ],
            options={
                'db_table': 'dependencias_movil',
            },
        ),
        migrations.CreateModel(
            name='CalificacionesMovil',
            fields=[
                ('id_Calf', models.AutoField(primary_key=True, serialize=False)),
                ('calificacion', models.IntegerField()),
                ('observacion', models.TextField(blank=True, null=True)),
                ('id_ActAlum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home_empleado.actividadalumnosmovil')),
                ('id_Alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home_empleado.alumnosmovil')),
            ],
            options={
                'db_table': 'calificaciones_movil',
            },
        ),
        migrations.CreateModel(
            name='AsistenciaMovil',
            fields=[
                ('id_Asistencia', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('usuario', models.TextField()),
                ('horaEntrada', models.TimeField()),
                ('horaSalida', models.TimeField()),
                ('Asistencia', models.BooleanField()),
                ('id_Profesor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home_empleado.usuariosmovil')),
            ],
            options={
                'db_table': 'asistencia_movil',
            },
        ),
        migrations.AddField(
            model_name='alumnosmovil',
            name='id_Maestro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home_empleado.usuariosmovil'),
        ),
        migrations.AddField(
            model_name='actividadacompmovil',
            name='id_Usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home_empleado.usuariosmovil'),
        ),
        migrations.CreateModel(
            name='ActCAPMovil',
            fields=[
                ('id_ActCAP', models.AutoField(primary_key=True, serialize=False)),
                ('NumCapacitacion', models.IntegerField()),
                ('TEMA', models.TextField()),
                ('ClaveRegion', models.TextField()),
                ('NombreRegion', models.TextField()),
                ('FechaProgramada', models.DateField()),
                ('Estado', models.TextField()),
                ('Reporte', models.TextField()),
                ('id_Usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home_empleado.usuariosmovil')),
            ],
            options={
                'db_table': 'act_cap_movil',
            },
        ),
    ]
