# Generated by Django 4.2.4 on 2025-01-08 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home_empleado', '0002_actividadacompmovil_actividadalumnosmovil_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventocalendario',
            name='usuario',
        ),
        migrations.DeleteModel(
            name='CapacitacionInical',
        ),
        migrations.DeleteModel(
            name='EventoCalendario',
        ),
    ]
