# Generated by Django 4.2.4 on 2025-01-18 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home_empleado', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='actcapmovil',
            table='ActCap_Movil',
        ),
    ]
