# Generated by Django 4.2.4 on 2025-01-09 01:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_dot', '0038_alter_datosusuario_id_comunidad'),
        ('home_empleado', '0003_remove_eventocalendario_usuario_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuariosmovil',
            name='usuariomovil',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='modulo_dot.usuario'),
        ),
    ]
