# Generated by Django 4.2.4 on 2025-01-21 05:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_apec', '0004_rename_nombre_comunidad_nombre_comunidad_and_more'),
        ('modulo_dot', '0001_initial'),
        ('home_empleado', '0003_alter_actcapmovil_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actcap',
            name='estado',
            field=models.CharField(blank=True, db_column='estado', max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='actcap',
            name='fecha_programada',
            field=models.CharField(blank=True, db_column='fecha_programada', max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='actcap',
            name='id_cct',
            field=models.ForeignKey(blank=True, db_column='id_cct', null=True, on_delete=django.db.models.deletion.CASCADE, to='modulo_apec.comunidad'),
        ),
        migrations.AlterField(
            model_name='actcap',
            name='id_microregion',
            field=models.ForeignKey(blank=True, db_column='id_microregion', null=True, on_delete=django.db.models.deletion.CASCADE, to='modulo_apec.microrregion'),
        ),
        migrations.AlterField(
            model_name='actcap',
            name='id_region',
            field=models.ForeignKey(blank=True, db_column='id_region', null=True, on_delete=django.db.models.deletion.CASCADE, to='modulo_apec.region'),
        ),
        migrations.AlterField(
            model_name='actcap',
            name='id_usuario',
            field=models.ForeignKey(blank=True, db_column='id_usuario', null=True, on_delete=django.db.models.deletion.CASCADE, to='modulo_dot.usuario'),
        ),
        migrations.AlterField(
            model_name='actcap',
            name='num_capacitacion',
            field=models.IntegerField(blank=True, db_column='num_capacitacion', null=True),
        ),
        migrations.AlterField(
            model_name='actcap',
            name='reporte',
            field=models.BinaryField(blank=True, db_column='reporte', null=True),
        ),
        migrations.AlterField(
            model_name='actcap',
            name='tema',
            field=models.CharField(blank=True, db_column='tema', max_length=200, null=True),
        ),
    ]
