# Generated by Django 4.2.4 on 2024-12-12 20:50

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_dot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DatosPersonales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('apellidopa', models.CharField(max_length=255)),
                ('apellidoma', models.CharField(max_length=255)),
                ('edad', models.IntegerField()),
                ('sexo', models.CharField(choices=[('Masculino', 'Masculino'), ('Femenino', 'Femenino'), ('Otro', 'Otro')], max_length=50)),
                ('correo', models.EmailField(max_length=254, unique=True)),
                ('telefono', models.CharField(max_length=50)),
                ('formacion_academica', models.CharField(max_length=255)),
                ('curp', models.CharField(max_length=18, unique=True)),
                ('fotografia', models.ImageField(upload_to='fotografias_personales/')),
            ],
            options={
                'db_table': 'datos_personales',
            },
        ),
        migrations.CreateModel(
            name='DocumentosPersonales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificacion_oficial', models.FileField(upload_to='documentos_identificacion/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'png'])])),
                ('comprobante_domicilio', models.FileField(upload_to='documentos_domicilio/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'png'])])),
                ('certificado_estudio', models.FileField(upload_to='documentos_estudio/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'png'])])),
                ('datos_personales', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='modulo_dot.datospersonales')),
            ],
            options={
                'verbose_name': 'Documento Personal',
                'verbose_name_plural': 'Documentos Personales',
                'db_table': 'documentos_personales',
            },
        ),
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(choices=[('CT', 'Coordinador Territorial'), ('DECB', 'Dirección de Educación Comunitaria e Inclusión Social'), ('DPE', 'Dirección de Planeación y Evaluación'), ('EC', 'Educador Comunitario'), ('ECA', 'Educador Comunitario de Acompañamiento Microrregional'), ('ECAR', 'Educador Comunitario de Acompañamiento Regional'), ('APEC', 'Asesor de Promoción y Educación Comunitaria')], max_length=10, unique=True)),
            ],
            options={
                'db_table': 'roles',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(max_length=255, unique=True)),
                ('contrasenia', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'usuario',
            },
        ),
        migrations.DeleteModel(
            name='Empleado',
        ),
        migrations.AddField(
            model_name='roles',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='modulo_dot.usuario'),
        ),
        migrations.AddField(
            model_name='datospersonales',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modulo_dot.usuario'),
        ),
    ]
