# Generated by Django 4.2.4 on 2024-12-12 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_dot', '0002_datospersonales_documentospersonales_roles_usuario_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datospersonales',
            name='fotografia',
            field=models.ImageField(blank=True, null=True, upload_to='fotografias_personales/'),
        ),
    ]
