# Generated by Django 4.2.4 on 2024-12-12 22:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('modulo_dot', '0004_rename_usuario_usuario_username_usuario_usuario_rol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='usuario_rol',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
