# Generated by Django 4.2.4 on 2024-12-12 22:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_dot', '0005_alter_usuario_usuario_rol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentospersonales',
            name='certificado_estudio',
            field=models.FileField(blank=True, null=True, upload_to='documentos_estudio/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'png'])]),
        ),
        migrations.AlterField(
            model_name='documentospersonales',
            name='comprobante_domicilio',
            field=models.FileField(blank=True, null=True, upload_to='documentos_domicilio/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'png'])]),
        ),
        migrations.AlterField(
            model_name='documentospersonales',
            name='identificacion_oficial',
            field=models.FileField(blank=True, null=True, upload_to='documentos_identificacion/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'png'])]),
        ),
    ]
