# Generated by Django 4.2.4 on 2024-12-12 22:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_dot', '0008_alter_roles_rol'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='username',
            new_name='usuario',
        ),
    ]
