# Generated by Django 4.2.4 on 2024-12-13 00:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_dot', '0011_alter_usuario_usuario_rol'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datospersonales',
            name='usuario',
        ),
    ]
