# Generated by Django 4.2.4 on 2024-12-13 00:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_dot', '0013_datospersonales_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datospersonales',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modulo_dot.usuario'),
        ),
    ]
