# Generated by Django 4.2.4 on 2024-12-15 02:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_dot', '0014_alter_datospersonales_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datospersonales',
            name='usuario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='modulo_dot.usuario'),
        ),
        migrations.AlterField(
            model_name='documentospersonales',
            name='datos_personales',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='modulo_dot.datospersonales'),
        ),
    ]
