# Generated by Django 4.2.4 on 2024-12-15 03:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_dot', '0015_alter_datospersonales_usuario_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='usuario',
            table=None,
        ),
    ]
