# Generated by Django 4.2.4 on 2024-12-15 03:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_dot', '0017_alter_usuario_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='usuario',
            table=None,
        ),
    ]
