# Generated by Django 4.2.4 on 2024-12-15 03:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_dot', '0018_alter_usuario_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='usuario',
            table='usuario',
        ),
    ]
