# Generated by Django 4.2.4 on 2024-12-22 02:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_dot', '0020_alter_usuario_usuario_rol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datospersonales',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='modulo_dot.usuario'),
        ),
    ]
