# Generated by Django 4.2.4 on 2024-12-22 21:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('form_app', '0006_alter_aspirante_datos_personales'),
        ('modulo_dot', '0021_alter_datospersonales_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='datospersonales',
            name='aspirante',
            field=models.OneToOneField(default=4, on_delete=django.db.models.deletion.CASCADE, related_name='datos_personales_info', to='form_app.aspirante'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='datospersonales',
            name='usuario',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='modulo_dot.usuario'),
        ),
    ]
