# Generated by Django 4.2.4 on 2024-12-22 21:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('form_app', '0006_alter_aspirante_datos_personales'),
        ('modulo_dot', '0022_datospersonales_aspirante_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datospersonales',
            name='aspirante',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='form_app.aspirante'),
        ),
    ]
