# Generated by Django 4.2.4 on 2024-12-23 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_dot', '0029_alter_usuario_contrasenia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='contrasenia',
            field=models.CharField(max_length=255),
        ),
    ]
