# Generated by Django 4.2.4 on 2024-12-23 01:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_dot', '0031_alter_usuario_contrasenia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datospersonales',
            name='aspirante',
        ),
        migrations.AlterField(
            model_name='datospersonales',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='modulo_dot.usuario'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='contrasenia',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='usuario',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
