# Generated by Django 4.2.4 on 2024-12-25 01:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_dot', '0034_alter_usuario_usuario_rol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datospersonales',
            name='usuario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='modulo_dot.usuario'),
        ),
    ]
