# Generated by Django 4.2.4 on 2025-01-06 17:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_dot', '0036_alter_usuario_usuario_rol'),
    ]

    operations = [
        migrations.CreateModel(
            name='DatosUsuario',
            fields=[
                ('id_Datos', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='Clave única del municipio')),
                ('nombreCompleto', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('situacion_Educativa', models.CharField(blank=True, max_length=255, null=True)),
                ('tipoServicio', models.CharField(blank=True, max_length=255, null=True)),
                ('contexto', models.CharField(blank=True, max_length=255, null=True)),
                ('Estado', models.CharField(blank=True, max_length=255, null=True)),
                ('id_comunidad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='modulo_dot.usuario')),
            ],
            options={
                'db_table': 'datos_usuario',
            },
        ),
        migrations.CreateModel(
            name='UsuariosApi',
            fields=[
                ('id_Usuario', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='Clave única del usuario')),
                ('usuario_api', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('password', models.CharField(blank=True, max_length=255, null=True)),
                ('rol', models.CharField(blank=True, max_length=255, null=True)),
                ('id_Datos', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='modulo_dot.datosusuario')),
            ],
            options={
                'db_table': 'usuario_api',
            },
        ),
    ]
