# Generated by Django 4.2.4 on 2025-01-06 17:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_apec', '0007_remove_comunidad_cantidad_alumnos'),
        ('modulo_dot', '0037_datosusuario_usuariosapi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datosusuario',
            name='id_comunidad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='modulo_apec.comunidad'),
        ),
    ]
