# Generated by Django 4.2.4 on 2025-01-15 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_dot', '0038_alter_datosusuario_id_comunidad'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuariosapi',
            name='id_Datos',
        ),
        migrations.DeleteModel(
            name='DatosUsuario',
        ),
        migrations.DeleteModel(
            name='UsuariosApi',
        ),
    ]
