# Generated by Django 4.2.4 on 2025-01-18 17:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CalendarEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('inicio_ciclo', 'Inicio de Ciclo Escolar'), ('termino_ciclo', 'Término de Ciclo Escolar'), ('colegiado_regional', 'Colegiado Regional'), ('colegiado_microrregional', 'Colegiado Microrregional'), ('promocion_captacion', 'Promoción y Captación'), ('capacitacion', 'Capacitación')], max_length=50)),
                ('date', models.DateField()),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_date', models.DateField()),
                ('payment_type', models.CharField(choices=[('movilidad', 'Movilidad'), ('hospedaje', 'Hospedaje y alimentos para la formación'), ('continuidad', 'Continuidad de estudios'), ('conectividad', 'Conectividad móvil'), ('vestuario', 'Vestuario de identidad'), ('atencion_medica', 'Atención médica'), ('fin_de_año', 'Apoyo económico de fin de año'), ('fallecimiento', 'Apoyo a beneficiarios por fallecimiento')], max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('status', models.CharField(default='pendiente', max_length=20)),
                ('signature', models.ImageField(blank=True, null=True, upload_to='signatures/')),
                ('assigned_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments_assigned_by', to=settings.AUTH_USER_MODEL)),
                ('assigned_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments_assigned_to', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('payment_schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial_pagos', to='modulo_DECB.paymentschedule')),
            ],
        ),
    ]
