# Generated by Django 4.2.4 on 2025-01-19 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_DECB', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentschedule',
            name='payment_type',
            field=models.CharField(choices=[('movilidad', 'Movilidad'), ('hospedaje', 'Hospedaje y alimentos para la formación'), ('continuidad', 'Continuidad de estudios'), ('conectividad', 'Conectividad móvil'), ('vestuario', 'Vestuario de identidad'), ('atencion_medica', 'Atención médica'), ('fin_de_año', 'Apoyo económico de fin de año'), ('fallecimiento', 'Apoyo a beneficiarios por fallecimiento'), ('EC_INIT', 'Educador Comunitario de Inicial'), ('EC', 'Educador Comunitario de Preescolar, Primaria y Secundaria'), ('ECA', 'Educador Comunitario de Acompañamiento'), ('ECAR', 'Educador Comunitario de Acompañamiento Regional')], max_length=50),
        ),
        migrations.AlterField(
            model_name='paymentschedule',
            name='status',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('procesado', 'Procesado'), ('rechazado', 'Rechazado'), ('completado', 'Completado'), ('completado-inicial', 'Completado-Inicial')], default='pendiente', max_length=20),
        ),
    ]
