# Generated by Django 4.2.4 on 2025-01-19 04:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_DECB', '0002_alter_paymentschedule_payment_type_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='calendarevent',
            table='calendar_event',
        ),
        migrations.AlterModelTable(
            name='paymenthistory',
            table='payment_history',
        ),
        migrations.AlterModelTable(
            name='paymentschedule',
            table='payment_schedule',
        ),
    ]
