# Generated by Django 4.2.4 on 2025-01-19 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_DECB', '0006_remove_paymentschedule_payment_date_pay'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentschedule',
            name='payment_date_pay',
            field=models.DateField(blank=True, null=True),
        ),
    ]
